config/routes.rb
RedactedRails::Application.routes.draw do

  get "password_resets/new"

  root :to => 'pages#home'

  match 'about' => 'pages#about'
  match 'contact' => 'pages#contact'

  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  match 'hosting' => 'hosting#show'

  resources :users
  resources :sessions
  resources :hosting
  resources :password_resets

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :first_name, :last_name, :email, :password, :password_confirmation

  has_secure_password
  validates_presence_of :password, :on => :create
  before_create { generate_token(:auth_token) }

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
end

# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #force_ssl

  private
    def current_user
      @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
    end

    helper_method :current_user
end

app/controllers/hosting_controller.rb
class HostingController < ApplicationController

  def show
    @title = "hosting"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
   @title = "let's play!"
	end

  def about
    @title = "about"
  end

  def contact
    @title = "contact"
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Password reset sent to #{params[:email]}"
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired"
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset."
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "log in"
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to user_path(user.id), :notice => "Let's play!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    logout_if_possible
    @title = "register"
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
   
    @title = "#{@user.first_name.capitalize}'s Dashboard"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the party!"
      redirect_to @user
    else
      @title = "register"
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "redacted inc."

    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  # def dashboard
  #   #binding.pry
  #   if current_user.nil?
  #     link_to "login", login_path
  #   else
  #     link_to current_user.first_name.capitalize, user_path(current_user.id)
  #   end
  # end

  def flash_helper
    f_names = [:notice, :warning, :message]
    fl = ''

    for name in f_names
      if flash[name]
        fl = fl + "<div class=\"notice\">#{flash[name]}</div>"
      end
      flash[name] = nil;
    end
  return fl
  end
end

app/helpers/hosting_helper.rb
module HostingHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(
      user.email.downcase,
      :alt => "Gravatar",
      :class => 'gravatar',
      :gravatar => options
      )
  end
end

app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    title
      = title

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    == render :partial => 'shared/header'
    .wrapper
      == flash_helper

      == yield
      
    == render :partial => 'shared/footer'
    == debug(params) if Rails.env.development?

app/views/pages/about.html.slim
h1 what we're all about

p Redacted is about making hosting powerful and easy to deploy.

app/views/pages/contact.html.slim
h1 let's chat
p Fill out the form below and we'll have someone contact you within one business day.

app/views/pages/home.html.slim
h1 simple and powerful game hosting
p Stop wasting time in configuration panels. Our services give the control of a dedicated server without the maitenance.

h3 what do I need to do?
h6
  ol
    li
      == link_to "Register an account", register_path
    li Choose a game.
    li Fork an existing repo or push your own.
    li Start playing!

app/views/password_resets/edit.html.slim
fieldset
  legend Reset Password
  - form_for @user, :url => password_reset_path(params[:id]) do |f|
    - if @user.errors.any?
      h2 Form is invaild.
      ul
        - for message in @user.errors.full_messages
          li == message
    .field
      == f.label :password
      == f.password_field :password
    .field
      == f.label :password_confirmation
      == f.password_field :password_confirmation
    .actions == f.submit "Update Password"

app/views/password_resets/new.html.slim
fieldset
  legend Reset Password
  == form_tag password_resets_path, :method => :post do
    .field
      == label_tag :email
      == text_field_tag :email, params[:email]
    .actions == submit_tag "Reset Password"

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    h2
      == pluralize(@user.errors.count, "error")
      |  prohibited this user from being saved:
    ul
      - @user.errors.full_messages.each do |msg|
        li == msg

app/views/shared/_footer.html.slim
footer.site-footer
  /
	 | copyright&nbsp;
	 = Time.now.year

app/views/shared/_header.html.slim
header.site-header
  .logo == link_to "redacted inc.", root_path
  nav.site-navigation
    == render_navigation
    | |&nbsp&nbsp
    == render :partial => 'shared/account_menu'
    span
      

app/views/users/new.html.slim
fieldset
  legend sign up
  - form_for @user do |f|
    == render 'shared/error_messages'
    .field
      == f.label :first_name
      == f.text_field :first_name, :placeholder => "First Name"
    .field
      == f.label :last_name
      == f.text_field :last_name, :placeholder => "Last Name"
    .field
      == f.label :email
      == f.text_field :email, :placeholder => "Email"
    .field
      == f.label :password
      == f.password_field :password
    .field
      == f.label :password_confirmation
      == f.password_field :password_confirmation
    .actions == f.submit "Register"

app/views/users/show.html.slim
.profile
  h1
    == gravatar_for @user
    == "#{@user.first_name.capitalize} #{@user.last_name.capitalize}"
  h2
    == @user.email

  fieldset.services
    legend services